
services:
  cong-thong-tin-apec-global:
    container_name: cong-thong-tin-apec-global
    image: cong-thong-tin-apec-global
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
        - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        - NEXT_PUBLIC_IMAGEKIT_PUBLIC_KEY=${NEXT_PUBLIC_IMAGEKIT_PUBLIC_KEY}
        - IMAGEKIT_PRIVATE_KEY=${IMAGEKIT_PRIVATE_KEY}
        - NEXT_PUBLIC_IMAGEKIT_URL_ENDPOINT=${NEXT_PUBLIC_IMAGEKIT_URL_ENDPOINT}

    env_file:
      - .env  
    ports:
      - "127.0.0.1:3015:3015"

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:3015"]
      interval: 30s
      timeout: 5s
      retries: 3

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
